import { Characters } from "./schema";

export const dataCharacters: Characters = [
  {
    id: "01ARZ3NDEKTSV4RRFFQ69G5FAV",
    name: "Harry Potter",
    slug: "harry-potter",
    alternateNames: "The Boy Who Lived",
    species: "human",
    gender: "male",
    hogwartsHouseSlug: "gryffindor",
    birthDate: new Date("1980-07-31"),
    birthYear: 1980,
    isWizard: true,
    ancestry: "half-blood",
    eyeColour: "green",
    hairColour: "black",
    wands: [
      {
        id: "01ARZ3NDEKTSV4RRFFQ69G5FI3",
        name: "Harry Potter Holly",
        slug: "harry-potter-holly",
        wood: "holly",
        core: "phoenix tail feather",
        length: 11,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "01FZ8ZC8YJ9Q0X7X4ZK2T3K4K5",
        name: "Harry Potter Pare",
        slug: "harry-potter-pare",
        wood: "pare",
        core: "unicorn pare horn",
        length: 11,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "01FZ8ZC8YJ9Q0X7X4ZK2T3K4K6",
        name: "Harry Potter Corn",
        slug: "harry-potter-corn",
        wood: "corn",
        core: "lizard horn corn",
        length: 11,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
    patronus: "stag",
    isHogwartsStudent: true,
    isHogwartsStaff: false,
    actor: "Daniel Radcliffe",
    alternateActors: "",
    isAlive: true,
    imageUrl: "https://ik.imagekit.io/hpapi/harry.jpg",
    createdAt: new Date(),
    updatedAt: new Date(),
    // alternateNames: ["The Boy Who Lived", "The Chosen One", "Undesirable No. 1", "Potty"],
    // alternateActors: [],
  },
  {
    id: "01ARZ3NDEKTSV4RRFFQ69G5FBW",
    name: "Hermione Granger",
    slug: "hermione-granger",
    alternateNames: "Hermy",
    species: "human",
    gender: "female",
    hogwartsHouseSlug: "gryffindor",
    birthDate: new Date("1979-09-19"),
    birthYear: 1979,
    isWizard: true,
    ancestry: "muggleborn",
    eyeColour: "brown",
    hairColour: "brown",
    wands: [
      {
        id: "01ARZ3NDEKTSV4RRFFQ69G5FG1",
        name: "Hermione Granger Vine",
        slug: "hermione-granger-vine",
        wood: "vine",
        core: "dragon heartstring",
        length: 10.75,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
    patronus: "otter",
    isHogwartsStudent: true,
    isHogwartsStaff: false,
    actor: "Emma Watson",
    alternateActors: "",
    isAlive: true,
    imageUrl: "https://ik.imagekit.io/hpapi/hermione.jpeg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "01ARZ3NDEKTSV4RRFFQ69G5FCX",
    name: "Ron Weasley",
    slug: "ron-weasley",
    alternateNames: "Dragomir Despard",
    species: "human",
    gender: "male",
    hogwartsHouseSlug: "gryffindor",
    birthDate: new Date("1980-03-01"),
    birthYear: 1980,
    isWizard: true,
    ancestry: "pure-blood",
    eyeColour: "blue",
    hairColour: "red",
    wands: [
      {
        id: "01ARZ3NDEKTSV4RRFFQ69G5FCY",
        name: "Ron Weasley Willow",
        slug: "ron-weasley-willow",
        wood: "willow",
        core: "unicorn tail hair",
        length: 14,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
    patronus: "Jack Russell terrier",
    isHogwartsStudent: true,
    isHogwartsStaff: false,
    actor: "Rupert Grint",
    alternateActors: "",
    isAlive: true,
    imageUrl: "https://ik.imagekit.io/hpapi/ron.jpg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "01ARZ3NDEKTSV4RRFFQ69G5FDY",
    name: "Draco Malfoy",
    slug: "draco-malfoy",
    alternateNames: "",
    species: "human",
    gender: "male",
    hogwartsHouseSlug: "slytherin",
    birthDate: new Date("1980-06-05"),
    birthYear: 1980,
    isWizard: true,
    ancestry: "pure-blood",
    eyeColour: "grey",
    hairColour: "blonde",
    wands: [
      {
        id: "01ARZ3NDEKTSV4RRFFQ69G5FDC",
        name: "Draco Malfoy Hawthorn",
        slug: "draco-malfoy-hawthorn",
        wood: "hawthorn",
        core: "unicorn tail hair",
        length: 10,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
    patronus: null,
    isHogwartsStudent: true,
    isHogwartsStaff: false,
    actor: "Tom Felton",
    alternateActors: "",
    isAlive: true,
    imageUrl: "https://ik.imagekit.io/hpapi/draco.jpg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "01ARZ3NDEKTSV4RRFFQ69G5FEZ",
    name: "Minerva McGonagall",
    slug: "minerva-mcgonagall",
    alternateNames: "",
    species: "human",
    gender: "female",
    hogwartsHouseSlug: "gryffindor",
    birthDate: new Date("1925-10-04"),
    birthYear: 1925,
    isWizard: true,
    ancestry: "half-blood",
    eyeColour: null,
    hairColour: "black",
    wands: [
      {
        id: "01ARZ3NDEKTSV4RRFFQ69G5FH2",
        name: "Minerva McGonagall Fir",
        slug: "minerva-mcgonagall-fir",
        wood: "fir",
        core: "dragon heartstring",
        length: 9.5,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
    patronus: "tabby cat",
    isHogwartsStudent: false,
    isHogwartsStaff: true,
    actor: "Dame Maggie Smith",
    alternateActors: "",
    isAlive: true,
    imageUrl: "https://ik.imagekit.io/hpapi/mcgonagall.jpg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
